from typing import Protocol, Self
from uuid import UUID

from scope_guard.modules.projects.domain import Project, ProjectCard, ProjectHistoryEntry


class ProjectRepository(Protocol):
    async def list_owned(self, owner: UUID) -> tuple[Project, ...]: ...
    async def get_owned(self, owner: UUID, identifier: UUID) -> Project | None: ...
    async def create(self, owner: UUID, card: ProjectCard) -> Project: ...
    async def update(self, owner: UUID, identifier: UUID, card: ProjectCard) -> Project | None: ...
    async def delete(self, owner: UUID, identifier: UUID) -> bool: ...


class HistoryRepository(Protocol):
    async def for_projects(
        self, identifiers: tuple[UUID, ...]
    ) -> tuple[ProjectHistoryEntry, ...]: ...


class ProjectWork(Protocol):
    @property
    def projects(self) -> ProjectRepository: ...
    @property
    def history(self) -> HistoryRepository: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    async def commit(self) -> None: ...
