from datetime import date, datetime
from typing import Protocol, Self
from uuid import UUID

from scope_guard.modules.drafts.values import (
    CreatedDraft,
    CreateDraft,
    DraftDocument,
    DraftHistory,
    DraftSummary,
    StoredDraft,
)


class DraftRepository(Protocol):
    async def list_owned(self, owner: UUID) -> tuple[DraftSummary, ...]: ...
    async def load_owned(self, owner: UUID, identifier: UUID) -> StoredDraft | None: ...
    async def lock_project(self, owner: UUID, identifier: UUID) -> bool: ...
    async def find_creation(self, owner: UUID, project: UUID, key: UUID) -> CreatedDraft | None: ...
    async def insert_history(self, owner: UUID, command: CreateDraft, day: date) -> UUID: ...
    async def insert_draft(
        self, owner: UUID, command: CreateDraft, history: UUID, now: datetime
    ) -> StoredDraft: ...
    async def mark_checked(self, owner: UUID, project: UUID, day: date) -> None: ...
    async def history_for_draft(self, owner: UUID, draft: StoredDraft) -> DraftHistory: ...
    async def update_document(
        self, owner: UUID, identifier: UUID, document: DraftDocument, now: datetime
    ) -> StoredDraft | None: ...


class DraftWork(Protocol):
    @property
    def drafts(self) -> DraftRepository: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    async def commit(self) -> None: ...
